### ISSUE TITLE
No leader elected

### ISSUE THREAD

**Issue by dffffffff** [bluzelle/swarmDB#17]
System
Raspberry Pi 2 Model B
Raspbian GNU/Linux 9.3 (stretch)

I followed the build instructions and spawned each node in separate screen shells with
ETHERSCAN_IO_API_TOKEN=MY_TOKEN ./the_db --address 0x006eae72077449caca91078ef78552c0cd9bce8f --port 58001
ETHERSCAN_IO_API_TOKEN=MY_TOKEN ./the_db --address 0x006eae72077449caca91078ef78552c0cd9bce8f --port 58002
etc

The first time all worked well and I could see the heartbeats from the leader node in its console. I could add a new value and see it propagate, however after shutting them all down (cltr-c) and doing the same thing over, no leader seems to be elected, they all have the text "I am follower" in their consoles. I rebooted the system and gave it another go with the same results.

**Comment by rnistuk** [comment]
Thanks for the bug report dffffffff, our RAFT implementation is definitely a work in progress at the moment and we are aware of Raspberry PI issues. I recently bought one so that I would be able to test our product with it. My issues have been a bit different from yours, but I will definitely attempt to recreate your situation and deal with it.

**Comment by amastracci** [comment]
Closed on devel branch
